package com.epocal.common.am;

import com.epocal.common.types.am.*;

import java.util.ArrayList;
import java.util.List;

/**
 * This class is a mirror of struct RealTimeQC defined in globals.h
 * to be compatible with Analytical Manager C++.
 * DO NOT EDIT THIS FILE without consulting with AM-C++ team first!
 */
public class RealTimeQC {
    public boolean enabled;
    public int startTime;
    public int intervalTime;
    public RealTimeQCType type;
    public int numPoints;
    public double extra1;
    public double extra2;
    public double extra3;
    public double extra4;
    public double extra5;
    public double extra6;
    public boolean continueIfFailed;
    public int humidityUntil;
    public List<HumidityStruct> humidityConfig;

    public RealTimeQC() {
        this.type = RealTimeQCType.ENUM_UNINITIALIZED;
        this.humidityConfig = new ArrayList();
    }

    @Override
    public String toString() {
        return "RealTimeQC{" +
                "enabled=" + enabled +
                ", startTime=" + startTime +
                ", intervalTime=" + intervalTime +
                ", type=" + type +
                ", numPoints=" + numPoints +
                ", extra1=" + extra1 +
                ", extra2=" + extra2 +
                ", extra3=" + extra3 +
                ", extra4=" + extra4 +
                ", extra5=" + extra5 +
                ", extra6=" + extra6 +
                ", continueIfFailed=" + continueIfFailed +
                ", humidityUntil=" + humidityUntil +
                ", humidityConfig=" + humidityConfig +
                '}';
    }
}