package com.epocal.common.am;

import com.epocal.common.types.am.*;

/**
 * This class is a mirror of struct SensorInfo defined in globals.h
 * to be compatible with Analytical Manager C++.
 * DO NOT EDIT THIS FILE without consulting with AM-C++ team first!
 */
public class SensorInfo {
    public ChannelType channelType;
    public Sensors sensorType;
    public byte sensorDescriptorNumber;         // TODO: Is there an enum to represent this?

    public double calDelimit;
    public double sampleDelimit;
    public double postDelimit;

    public double extrapolation;

    public double calWindowSize;
    public double sampleWindowSize;
    public double postWindowSize;

    public double calCurveWeight;
    public double sampleCurveWeight;

    public double calConcentration;
    public double offset;
    public double slopeFactor;

    public double CalMeanLowQC;
    public double CalMeanHighQC;
    public double CalDriftLowQC;
    public double CalDriftHighQC;
    public double CalSecondLowQC;
    public double CalSecondHighQC;
    public double CalNoiseHighQC;

    public double SampleMeanLowQC;
    public double SampleMeanHighQC;
    public double SampleDriftLowQC;
    public double SampleDriftHighQC;
    public double SampleSecondLowQC;
    public double SampleSecondHighQC;
    public double SampleNoiseHighQC;

    public double PostMeanLowQC;
    public double PostMeanHighQC;
    public double PostDriftLowQC;
    public double PostDriftHighQC;
    public double PostSecondLowQC;
    public double PostSecondHighQC;
    public double PostNoiseHighQC;

    public double DeltaDriftLowQC;
    public double DeltaDriftHighQC;

    public double param1;
    public double param2;
    public double param3;
    public double param4;
    public double param5;
    public double param6;
    public double param7;
    public double param8;
    public double param9;
    public double param10;

    public double param11;
    public double param12;
    public double param13;
    public double param14;
    public double param15;
    public double param16;
    public double param17;
    public double param18;
    public double param19;
    public double param20;
    public double param21;
    public double param22;
    public double param23;
    public double param24;
    public double param25;
    public double param26;
    public double param27;
    public double param28;
    public double param29;
    public double param30;

    public double param31;
    public double param32;
    public double param33;
    public double param34;
    public double param35;
    public double param36;
    public double param37;
    public double param38;
    public double param39;
    public double param40;
    public double param41;
    public double param42;
    public double param43;
    public double param44;
    public double param45;
    public double param46;
    public double param47;
    public double param48;
    public double param49;
    public double param50;

    public double param51;
    public double param52;
    public double param53;
    public double param54;
    public double param55;
    public double param56;
    public double param57;
    public double param58;
    public double param59;
    public double param60;
    public double param61;
    public double param62;
    public double param63;
    public double param64;
    public double param65;
    public double param66;
    public double param67;
    public double param68;
    public double param69;
    public double param70;
    public double param71;
    public double param72;
    public double param73;
    public double param74;
    public double param75;
    public double param76;
    public double param77;
    public double param78;
    public double param79;
    public double param80;
    public double param81;
    public double param82;
    public double param83;
    public double param84;
    public double param85;
    public double param86;
    public double param87;
    public double param88;
    public double param89;
    public double param90;
    public double param91;
    public double param92;
    public double param93;
    public double param94;
    public double param95;
    public double param96;
    public double param97;
    public double param98;
    public double param99;
    public double param100;

    public float readerMeanLow;
    public float readerMeanHigh;
    public float readerDriftLow;
    public float readerDriftHigh;
    public float readerNoiseLow;
    public float readerNoiseHigh;

    public double tMinus;
    public double tPlus;
    public double postCurvatureWeight;

    public int bloodPointsToSkip;
    public int bloodPointsInWindow;
    public double bloodNoiseHigh;

    public int aqPointsToSkip;
    public int aqPointsInWindow;
    public double aqNoiseHigh;

    public int lateBloodPointsToSkip;
    public int lateBloodPointsInWindow;
    public double lateBloodNoiseHigh;

    public int lateAqPointsToSkip;
    public int lateAqPointsInWindow;
    public double lateAqNoiseHigh;

    public double rtPointLimitLow;
    public double rtPointLimitHigh;
    public double d1Low;
    public double d1High;
    public double p1d2Low;
    public double p1d2High;
    public double p2d2Low;
    public double p2d2High;
    public double p3d2Low;
    public double p3d2High;

    public double A;
    public double B;
    public double C;
    public double D;
    public double F;
    public double G;
    public double TAmbOffset;
    public double InjectionTimeOffset;
    public double AgeOffset;
    public double PowerOffset;

    public String NeuralNetBlood;
    public String NeuralNetAQ;

    public SensorInfo() {
        this.channelType = ChannelType.ENUM_UNINITIALIZED;
        this.sensorType = Sensors.ENUM_UNINITIALIZED;
    }

    @Override
    public String toString() {
        return "SensorInfo{" +
                "channelType=" + channelType +
                ", sensorType=" + sensorType +
                ", sensorDescriptorNumber=" + sensorDescriptorNumber +
                ", calDelimit=" + calDelimit +
                ", sampleDelimit=" + sampleDelimit +
                ", postDelimit=" + postDelimit +
                ", extrapolation=" + extrapolation +
                ", calWindowSize=" + calWindowSize +
                ", sampleWindowSize=" + sampleWindowSize +
                ", postWindowSize=" + postWindowSize +
                ", calCurveWeight=" + calCurveWeight +
                ", sampleCurveWeight=" + sampleCurveWeight +
                ", calConcentration=" + calConcentration +
                ", offset=" + offset +
                ", slopeFactor=" + slopeFactor +
                ", CalMeanLowQC=" + CalMeanLowQC +
                ", CalMeanHighQC=" + CalMeanHighQC +
                ", CalDriftLowQC=" + CalDriftLowQC +
                ", CalDriftHighQC=" + CalDriftHighQC +
                ", CalSecondLowQC=" + CalSecondLowQC +
                ", CalSecondHighQC=" + CalSecondHighQC +
                ", CalNoiseHighQC=" + CalNoiseHighQC +
                ", SampleMeanLowQC=" + SampleMeanLowQC +
                ", SampleMeanHighQC=" + SampleMeanHighQC +
                ", SampleDriftLowQC=" + SampleDriftLowQC +
                ", SampleDriftHighQC=" + SampleDriftHighQC +
                ", SampleSecondLowQC=" + SampleSecondLowQC +
                ", SampleSecondHighQC=" + SampleSecondHighQC +
                ", SampleNoiseHighQC=" + SampleNoiseHighQC +
                ", PostMeanLowQC=" + PostMeanLowQC +
                ", PostMeanHighQC=" + PostMeanHighQC +
                ", PostDriftLowQC=" + PostDriftLowQC +
                ", PostDriftHighQC=" + PostDriftHighQC +
                ", PostSecondLowQC=" + PostSecondLowQC +
                ", PostSecondHighQC=" + PostSecondHighQC +
                ", PostNoiseHighQC=" + PostNoiseHighQC +
                ", DeltaDriftLowQC=" + DeltaDriftLowQC +
                ", DeltaDriftHighQC=" + DeltaDriftHighQC +
                ", param1=" + param1 +
                ", param2=" + param2 +
                ", param3=" + param3 +
                ", param4=" + param4 +
                ", param5=" + param5 +
                ", param6=" + param6 +
                ", param7=" + param7 +
                ", param8=" + param8 +
                ", param9=" + param9 +
                ", param10=" + param10 +
                ", param11=" + param11 +
                ", param12=" + param12 +
                ", param13=" + param13 +
                ", param14=" + param14 +
                ", param15=" + param15 +
                ", param16=" + param16 +
                ", param17=" + param17 +
                ", param18=" + param18 +
                ", param19=" + param19 +
                ", param20=" + param20 +
                ", param21=" + param21 +
                ", param22=" + param22 +
                ", param23=" + param23 +
                ", param24=" + param24 +
                ", param25=" + param25 +
                ", param26=" + param26 +
                ", param27=" + param27 +
                ", param28=" + param28 +
                ", param29=" + param29 +
                ", param30=" + param30 +
                ", param31=" + param31 +
                ", param32=" + param32 +
                ", param33=" + param33 +
                ", param34=" + param34 +
                ", param35=" + param35 +
                ", param36=" + param36 +
                ", param37=" + param37 +
                ", param38=" + param38 +
                ", param39=" + param39 +
                ", param40=" + param40 +
                ", param41=" + param41 +
                ", param42=" + param42 +
                ", param43=" + param43 +
                ", param44=" + param44 +
                ", param45=" + param45 +
                ", param46=" + param46 +
                ", param47=" + param47 +
                ", param48=" + param48 +
                ", param49=" + param49 +
                ", param50=" + param50 +
                ", param51=" + param51 +
                ", param52=" + param52 +
                ", param53=" + param53 +
                ", param54=" + param54 +
                ", param55=" + param55 +
                ", param56=" + param56 +
                ", param57=" + param57 +
                ", param58=" + param58 +
                ", param59=" + param59 +
                ", param60=" + param60 +
                ", param61=" + param61 +
                ", param62=" + param62 +
                ", param63=" + param63 +
                ", param64=" + param64 +
                ", param65=" + param65 +
                ", param66=" + param66 +
                ", param67=" + param67 +
                ", param68=" + param68 +
                ", param69=" + param69 +
                ", param70=" + param70 +
                ", param71=" + param71 +
                ", param72=" + param72 +
                ", param73=" + param73 +
                ", param74=" + param74 +
                ", param75=" + param75 +
                ", param76=" + param76 +
                ", param77=" + param77 +
                ", param78=" + param78 +
                ", param79=" + param79 +
                ", param80=" + param80 +
                ", param81=" + param81 +
                ", param82=" + param82 +
                ", param83=" + param83 +
                ", param84=" + param84 +
                ", param85=" + param85 +
                ", param86=" + param86 +
                ", param87=" + param87 +
                ", param88=" + param88 +
                ", param89=" + param89 +
                ", param90=" + param90 +
                ", param91=" + param91 +
                ", param92=" + param92 +
                ", param93=" + param93 +
                ", param94=" + param94 +
                ", param95=" + param95 +
                ", param96=" + param96 +
                ", param97=" + param97 +
                ", param98=" + param98 +
                ", param99=" + param99 +
                ", param100=" + param100 +
                ", readerMeanLow=" + readerMeanLow +
                ", readerMeanHigh=" + readerMeanHigh +
                ", readerDriftLow=" + readerDriftLow +
                ", readerDriftHigh=" + readerDriftHigh +
                ", readerNoiseLow=" + readerNoiseLow +
                ", readerNoiseHigh=" + readerNoiseHigh +
                ", tMinus=" + tMinus +
                ", tPlus=" + tPlus +
                ", postCurvatureWeight=" + postCurvatureWeight +
                ", bloodPointsToSkip=" + bloodPointsToSkip +
                ", bloodPointsInWindow=" + bloodPointsInWindow +
                ", bloodNoiseHigh=" + bloodNoiseHigh +
                ", aqPointsToSkip=" + aqPointsToSkip +
                ", aqPointsInWindow=" + aqPointsInWindow +
                ", aqNoiseHigh=" + aqNoiseHigh +
                ", lateBloodPointsToSkip=" + lateBloodPointsToSkip +
                ", lateBloodPointsInWindow=" + lateBloodPointsInWindow +
                ", lateBloodNoiseHigh=" + lateBloodNoiseHigh +
                ", lateAqPointsToSkip=" + lateAqPointsToSkip +
                ", lateAqPointsInWindow=" + lateAqPointsInWindow +
                ", lateAqNoiseHigh=" + lateAqNoiseHigh +
                ", rtPointLimitLow=" + rtPointLimitLow +
                ", rtPointLimitHigh=" + rtPointLimitHigh +
                ", d1Low=" + d1Low +
                ", d1High=" + d1High +
                ", p1d2Low=" + p1d2Low +
                ", p1d2High=" + p1d2High +
                ", p2d2Low=" + p2d2Low +
                ", p2d2High=" + p2d2High +
                ", p3d2Low=" + p3d2Low +
                ", p3d2High=" + p3d2High +
                ", A=" + A +
                ", B=" + B +
                ", C=" + C +
                ", D=" + D +
                ", F=" + F +
                ", G=" + G +
                ", TAmbOffset=" + TAmbOffset +
                ", InjectionTimeOffset=" + InjectionTimeOffset +
                ", AgeOffset=" + AgeOffset +
                ", PowerOffset=" + PowerOffset +
                ", NeuralNetBlood=" + NeuralNetBlood +
                ", NeuralNetAQ=" + NeuralNetAQ +
                '}';
    }
}