// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coox_model.proto

#ifndef PROTOBUF_coox_5fmodel_2eproto__INCLUDED
#define PROTOBUF_coox_5fmodel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace to {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_coox_5fmodel_2eproto();
void protobuf_AssignDesc_coox_5fmodel_2eproto();
void protobuf_ShutdownFile_coox_5fmodel_2eproto();

class CooxModel;

// ===================================================================

class CooxModel : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:to.CooxModel) */ {
 public:
  CooxModel();
  virtual ~CooxModel();

  CooxModel(const CooxModel& from);

  inline CooxModel& operator=(const CooxModel& from) {
    CopyFrom(from);
    return *this;
  }

  static const CooxModel& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CooxModel* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CooxModel* other);

  // implements Message ----------------------------------------------

  inline CooxModel* New() const { return New(NULL); }

  CooxModel* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CooxModel& from);
  void MergeFrom(const CooxModel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CooxModel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 PixelMin = 1;
  void clear_pixelmin();
  static const int kPixelMinFieldNumber = 1;
  ::google::protobuf::int32 pixelmin() const;
  void set_pixelmin(::google::protobuf::int32 value);

  // optional int32 PixelMax = 2;
  void clear_pixelmax();
  static const int kPixelMaxFieldNumber = 2;
  ::google::protobuf::int32 pixelmax() const;
  void set_pixelmax(::google::protobuf::int32 value);

  // optional int32 CoeffStart = 3;
  void clear_coeffstart();
  static const int kCoeffStartFieldNumber = 3;
  ::google::protobuf::int32 coeffstart() const;
  void set_coeffstart(::google::protobuf::int32 value);

  // optional int32 CoeffEnd = 4;
  void clear_coeffend();
  static const int kCoeffEndFieldNumber = 4;
  ::google::protobuf::int32 coeffend() const;
  void set_coeffend(::google::protobuf::int32 value);

  // repeated float Coefficients0 = 5;
  int coefficients0_size() const;
  void clear_coefficients0();
  static const int kCoefficients0FieldNumber = 5;
  float coefficients0(int index) const;
  void set_coefficients0(int index, float value);
  void add_coefficients0(float value);
  const ::google::protobuf::RepeatedField< float >&
      coefficients0() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_coefficients0();

  // repeated float Coefficients1 = 6;
  int coefficients1_size() const;
  void clear_coefficients1();
  static const int kCoefficients1FieldNumber = 6;
  float coefficients1(int index) const;
  void set_coefficients1(int index, float value);
  void add_coefficients1(float value);
  const ::google::protobuf::RepeatedField< float >&
      coefficients1() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_coefficients1();

  // repeated float Coefficients2 = 7;
  int coefficients2_size() const;
  void clear_coefficients2();
  static const int kCoefficients2FieldNumber = 7;
  float coefficients2(int index) const;
  void set_coefficients2(int index, float value);
  void add_coefficients2(float value);
  const ::google::protobuf::RepeatedField< float >&
      coefficients2() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_coefficients2();

  // repeated float Coefficients3 = 8;
  int coefficients3_size() const;
  void clear_coefficients3();
  static const int kCoefficients3FieldNumber = 8;
  float coefficients3(int index) const;
  void set_coefficients3(int index, float value);
  void add_coefficients3(float value);
  const ::google::protobuf::RepeatedField< float >&
      coefficients3() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_coefficients3();

  // repeated float Coefficients4 = 9;
  int coefficients4_size() const;
  void clear_coefficients4();
  static const int kCoefficients4FieldNumber = 9;
  float coefficients4(int index) const;
  void set_coefficients4(int index, float value);
  void add_coefficients4(float value);
  const ::google::protobuf::RepeatedField< float >&
      coefficients4() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_coefficients4();

  // @@protoc_insertion_point(class_scope:to.CooxModel)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::int32 pixelmin_;
  ::google::protobuf::int32 pixelmax_;
  ::google::protobuf::int32 coeffstart_;
  ::google::protobuf::int32 coeffend_;
  ::google::protobuf::RepeatedField< float > coefficients0_;
  mutable int _coefficients0_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > coefficients1_;
  mutable int _coefficients1_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > coefficients2_;
  mutable int _coefficients2_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > coefficients3_;
  mutable int _coefficients3_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > coefficients4_;
  mutable int _coefficients4_cached_byte_size_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_coox_5fmodel_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_coox_5fmodel_2eproto();
  #endif
  friend void protobuf_AssignDesc_coox_5fmodel_2eproto();
  friend void protobuf_ShutdownFile_coox_5fmodel_2eproto();

  void InitAsDefaultInstance();
  static CooxModel* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CooxModel

// optional int32 PixelMin = 1;
inline void CooxModel::clear_pixelmin() {
  pixelmin_ = 0;
}
inline ::google::protobuf::int32 CooxModel::pixelmin() const {
  // @@protoc_insertion_point(field_get:to.CooxModel.PixelMin)
  return pixelmin_;
}
inline void CooxModel::set_pixelmin(::google::protobuf::int32 value) {
  
  pixelmin_ = value;
  // @@protoc_insertion_point(field_set:to.CooxModel.PixelMin)
}

// optional int32 PixelMax = 2;
inline void CooxModel::clear_pixelmax() {
  pixelmax_ = 0;
}
inline ::google::protobuf::int32 CooxModel::pixelmax() const {
  // @@protoc_insertion_point(field_get:to.CooxModel.PixelMax)
  return pixelmax_;
}
inline void CooxModel::set_pixelmax(::google::protobuf::int32 value) {
  
  pixelmax_ = value;
  // @@protoc_insertion_point(field_set:to.CooxModel.PixelMax)
}

// optional int32 CoeffStart = 3;
inline void CooxModel::clear_coeffstart() {
  coeffstart_ = 0;
}
inline ::google::protobuf::int32 CooxModel::coeffstart() const {
  // @@protoc_insertion_point(field_get:to.CooxModel.CoeffStart)
  return coeffstart_;
}
inline void CooxModel::set_coeffstart(::google::protobuf::int32 value) {
  
  coeffstart_ = value;
  // @@protoc_insertion_point(field_set:to.CooxModel.CoeffStart)
}

// optional int32 CoeffEnd = 4;
inline void CooxModel::clear_coeffend() {
  coeffend_ = 0;
}
inline ::google::protobuf::int32 CooxModel::coeffend() const {
  // @@protoc_insertion_point(field_get:to.CooxModel.CoeffEnd)
  return coeffend_;
}
inline void CooxModel::set_coeffend(::google::protobuf::int32 value) {
  
  coeffend_ = value;
  // @@protoc_insertion_point(field_set:to.CooxModel.CoeffEnd)
}

// repeated float Coefficients0 = 5;
inline int CooxModel::coefficients0_size() const {
  return coefficients0_.size();
}
inline void CooxModel::clear_coefficients0() {
  coefficients0_.Clear();
}
inline float CooxModel::coefficients0(int index) const {
  // @@protoc_insertion_point(field_get:to.CooxModel.Coefficients0)
  return coefficients0_.Get(index);
}
inline void CooxModel::set_coefficients0(int index, float value) {
  coefficients0_.Set(index, value);
  // @@protoc_insertion_point(field_set:to.CooxModel.Coefficients0)
}
inline void CooxModel::add_coefficients0(float value) {
  coefficients0_.Add(value);
  // @@protoc_insertion_point(field_add:to.CooxModel.Coefficients0)
}
inline const ::google::protobuf::RepeatedField< float >&
CooxModel::coefficients0() const {
  // @@protoc_insertion_point(field_list:to.CooxModel.Coefficients0)
  return coefficients0_;
}
inline ::google::protobuf::RepeatedField< float >*
CooxModel::mutable_coefficients0() {
  // @@protoc_insertion_point(field_mutable_list:to.CooxModel.Coefficients0)
  return &coefficients0_;
}

// repeated float Coefficients1 = 6;
inline int CooxModel::coefficients1_size() const {
  return coefficients1_.size();
}
inline void CooxModel::clear_coefficients1() {
  coefficients1_.Clear();
}
inline float CooxModel::coefficients1(int index) const {
  // @@protoc_insertion_point(field_get:to.CooxModel.Coefficients1)
  return coefficients1_.Get(index);
}
inline void CooxModel::set_coefficients1(int index, float value) {
  coefficients1_.Set(index, value);
  // @@protoc_insertion_point(field_set:to.CooxModel.Coefficients1)
}
inline void CooxModel::add_coefficients1(float value) {
  coefficients1_.Add(value);
  // @@protoc_insertion_point(field_add:to.CooxModel.Coefficients1)
}
inline const ::google::protobuf::RepeatedField< float >&
CooxModel::coefficients1() const {
  // @@protoc_insertion_point(field_list:to.CooxModel.Coefficients1)
  return coefficients1_;
}
inline ::google::protobuf::RepeatedField< float >*
CooxModel::mutable_coefficients1() {
  // @@protoc_insertion_point(field_mutable_list:to.CooxModel.Coefficients1)
  return &coefficients1_;
}

// repeated float Coefficients2 = 7;
inline int CooxModel::coefficients2_size() const {
  return coefficients2_.size();
}
inline void CooxModel::clear_coefficients2() {
  coefficients2_.Clear();
}
inline float CooxModel::coefficients2(int index) const {
  // @@protoc_insertion_point(field_get:to.CooxModel.Coefficients2)
  return coefficients2_.Get(index);
}
inline void CooxModel::set_coefficients2(int index, float value) {
  coefficients2_.Set(index, value);
  // @@protoc_insertion_point(field_set:to.CooxModel.Coefficients2)
}
inline void CooxModel::add_coefficients2(float value) {
  coefficients2_.Add(value);
  // @@protoc_insertion_point(field_add:to.CooxModel.Coefficients2)
}
inline const ::google::protobuf::RepeatedField< float >&
CooxModel::coefficients2() const {
  // @@protoc_insertion_point(field_list:to.CooxModel.Coefficients2)
  return coefficients2_;
}
inline ::google::protobuf::RepeatedField< float >*
CooxModel::mutable_coefficients2() {
  // @@protoc_insertion_point(field_mutable_list:to.CooxModel.Coefficients2)
  return &coefficients2_;
}

// repeated float Coefficients3 = 8;
inline int CooxModel::coefficients3_size() const {
  return coefficients3_.size();
}
inline void CooxModel::clear_coefficients3() {
  coefficients3_.Clear();
}
inline float CooxModel::coefficients3(int index) const {
  // @@protoc_insertion_point(field_get:to.CooxModel.Coefficients3)
  return coefficients3_.Get(index);
}
inline void CooxModel::set_coefficients3(int index, float value) {
  coefficients3_.Set(index, value);
  // @@protoc_insertion_point(field_set:to.CooxModel.Coefficients3)
}
inline void CooxModel::add_coefficients3(float value) {
  coefficients3_.Add(value);
  // @@protoc_insertion_point(field_add:to.CooxModel.Coefficients3)
}
inline const ::google::protobuf::RepeatedField< float >&
CooxModel::coefficients3() const {
  // @@protoc_insertion_point(field_list:to.CooxModel.Coefficients3)
  return coefficients3_;
}
inline ::google::protobuf::RepeatedField< float >*
CooxModel::mutable_coefficients3() {
  // @@protoc_insertion_point(field_mutable_list:to.CooxModel.Coefficients3)
  return &coefficients3_;
}

// repeated float Coefficients4 = 9;
inline int CooxModel::coefficients4_size() const {
  return coefficients4_.size();
}
inline void CooxModel::clear_coefficients4() {
  coefficients4_.Clear();
}
inline float CooxModel::coefficients4(int index) const {
  // @@protoc_insertion_point(field_get:to.CooxModel.Coefficients4)
  return coefficients4_.Get(index);
}
inline void CooxModel::set_coefficients4(int index, float value) {
  coefficients4_.Set(index, value);
  // @@protoc_insertion_point(field_set:to.CooxModel.Coefficients4)
}
inline void CooxModel::add_coefficients4(float value) {
  coefficients4_.Add(value);
  // @@protoc_insertion_point(field_add:to.CooxModel.Coefficients4)
}
inline const ::google::protobuf::RepeatedField< float >&
CooxModel::coefficients4() const {
  // @@protoc_insertion_point(field_list:to.CooxModel.Coefficients4)
  return coefficients4_;
}
inline ::google::protobuf::RepeatedField< float >*
CooxModel::mutable_coefficients4() {
  // @@protoc_insertion_point(field_mutable_list:to.CooxModel.Coefficients4)
  return &coefficients4_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_coox_5fmodel_2eproto__INCLUDED
