// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bge_parameters.proto

#ifndef PROTOBUF_bge_5fparameters_2eproto__INCLUDED
#define PROTOBUF_bge_5fparameters_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "sensor_readings.pb.h"
// @@protoc_insertion_point(includes)

namespace to {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_bge_5fparameters_2eproto();
void protobuf_AssignDesc_bge_5fparameters_2eproto();
void protobuf_ShutdownFile_bge_5fparameters_2eproto();

class BGEParameters;

// ===================================================================

class BGEParameters : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:to.BGEParameters) */ {
 public:
  BGEParameters();
  virtual ~BGEParameters();

  BGEParameters(const BGEParameters& from);

  inline BGEParameters& operator=(const BGEParameters& from) {
    CopyFrom(from);
    return *this;
  }

  static const BGEParameters& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const BGEParameters* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(BGEParameters* other);

  // implements Message ----------------------------------------------

  inline BGEParameters* New() const { return New(NULL); }

  BGEParameters* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BGEParameters& from);
  void MergeFrom(const BGEParameters& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BGEParameters* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double parameter0 = 1;
  void clear_parameter0();
  static const int kParameter0FieldNumber = 1;
  double parameter0() const;
  void set_parameter0(double value);

  // optional double parameter1 = 2;
  void clear_parameter1();
  static const int kParameter1FieldNumber = 2;
  double parameter1() const;
  void set_parameter1(double value);

  // optional float parameter2 = 3;
  void clear_parameter2();
  static const int kParameter2FieldNumber = 3;
  float parameter2() const;
  void set_parameter2(float value);

  // optional float parameter3 = 4;
  void clear_parameter3();
  static const int kParameter3FieldNumber = 4;
  float parameter3() const;
  void set_parameter3(float value);

  // optional bool parameter4 = 5;
  void clear_parameter4();
  static const int kParameter4FieldNumber = 5;
  bool parameter4() const;
  void set_parameter4(bool value);

  // optional int32 parameter5 = 6;
  void clear_parameter5();
  static const int kParameter5FieldNumber = 6;
  ::google::protobuf::int32 parameter5() const;
  void set_parameter5(::google::protobuf::int32 value);

  // optional .to.SensorReadings parameter6 = 7;
  bool has_parameter6() const;
  void clear_parameter6();
  static const int kParameter6FieldNumber = 7;
  const ::to::SensorReadings& parameter6() const;
  ::to::SensorReadings* mutable_parameter6();
  ::to::SensorReadings* release_parameter6();
  void set_allocated_parameter6(::to::SensorReadings* parameter6);

  // optional int32 parameter7 = 8;
  void clear_parameter7();
  static const int kParameter7FieldNumber = 8;
  ::google::protobuf::int32 parameter7() const;
  void set_parameter7(::google::protobuf::int32 value);

  // optional bool parameter8 = 9;
  void clear_parameter8();
  static const int kParameter8FieldNumber = 9;
  bool parameter8() const;
  void set_parameter8(bool value);

  // optional double parameter9 = 10;
  void clear_parameter9();
  static const int kParameter9FieldNumber = 10;
  double parameter9() const;
  void set_parameter9(double value);

  // optional int32 parameter10 = 11;
  void clear_parameter10();
  static const int kParameter10FieldNumber = 11;
  ::google::protobuf::int32 parameter10() const;
  void set_parameter10(::google::protobuf::int32 value);

  // optional double parameter11 = 12;
  void clear_parameter11();
  static const int kParameter11FieldNumber = 12;
  double parameter11() const;
  void set_parameter11(double value);

  // optional double parameter12 = 13;
  void clear_parameter12();
  static const int kParameter12FieldNumber = 13;
  double parameter12() const;
  void set_parameter12(double value);

  // optional double parameter13 = 14;
  void clear_parameter13();
  static const int kParameter13FieldNumber = 14;
  double parameter13() const;
  void set_parameter13(double value);

  // optional double parameter14 = 15;
  void clear_parameter14();
  static const int kParameter14FieldNumber = 15;
  double parameter14() const;
  void set_parameter14(double value);

  // optional bool parameter15 = 16;
  void clear_parameter15();
  static const int kParameter15FieldNumber = 16;
  bool parameter15() const;
  void set_parameter15(bool value);

  // optional bool parameter16 = 17;
  void clear_parameter16();
  static const int kParameter16FieldNumber = 17;
  bool parameter16() const;
  void set_parameter16(bool value);

  // optional int32 count = 18;
  void clear_count();
  static const int kCountFieldNumber = 18;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:to.BGEParameters)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  double parameter0_;
  double parameter1_;
  float parameter2_;
  float parameter3_;
  ::to::SensorReadings* parameter6_;
  ::google::protobuf::int32 parameter5_;
  ::google::protobuf::int32 parameter7_;
  double parameter9_;
  ::google::protobuf::int32 parameter10_;
  bool parameter4_;
  bool parameter8_;
  bool parameter15_;
  bool parameter16_;
  double parameter11_;
  double parameter12_;
  double parameter13_;
  double parameter14_;
  ::google::protobuf::int32 count_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_bge_5fparameters_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_bge_5fparameters_2eproto();
  #endif
  friend void protobuf_AssignDesc_bge_5fparameters_2eproto();
  friend void protobuf_ShutdownFile_bge_5fparameters_2eproto();

  void InitAsDefaultInstance();
  static BGEParameters* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BGEParameters

// optional double parameter0 = 1;
inline void BGEParameters::clear_parameter0() {
  parameter0_ = 0;
}
inline double BGEParameters::parameter0() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter0)
  return parameter0_;
}
inline void BGEParameters::set_parameter0(double value) {
  
  parameter0_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter0)
}

// optional double parameter1 = 2;
inline void BGEParameters::clear_parameter1() {
  parameter1_ = 0;
}
inline double BGEParameters::parameter1() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter1)
  return parameter1_;
}
inline void BGEParameters::set_parameter1(double value) {
  
  parameter1_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter1)
}

// optional float parameter2 = 3;
inline void BGEParameters::clear_parameter2() {
  parameter2_ = 0;
}
inline float BGEParameters::parameter2() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter2)
  return parameter2_;
}
inline void BGEParameters::set_parameter2(float value) {
  
  parameter2_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter2)
}

// optional float parameter3 = 4;
inline void BGEParameters::clear_parameter3() {
  parameter3_ = 0;
}
inline float BGEParameters::parameter3() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter3)
  return parameter3_;
}
inline void BGEParameters::set_parameter3(float value) {
  
  parameter3_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter3)
}

// optional bool parameter4 = 5;
inline void BGEParameters::clear_parameter4() {
  parameter4_ = false;
}
inline bool BGEParameters::parameter4() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter4)
  return parameter4_;
}
inline void BGEParameters::set_parameter4(bool value) {
  
  parameter4_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter4)
}

// optional int32 parameter5 = 6;
inline void BGEParameters::clear_parameter5() {
  parameter5_ = 0;
}
inline ::google::protobuf::int32 BGEParameters::parameter5() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter5)
  return parameter5_;
}
inline void BGEParameters::set_parameter5(::google::protobuf::int32 value) {
  
  parameter5_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter5)
}

// optional .to.SensorReadings parameter6 = 7;
inline bool BGEParameters::has_parameter6() const {
  return !_is_default_instance_ && parameter6_ != NULL;
}
inline void BGEParameters::clear_parameter6() {
  if (GetArenaNoVirtual() == NULL && parameter6_ != NULL) delete parameter6_;
  parameter6_ = NULL;
}
inline const ::to::SensorReadings& BGEParameters::parameter6() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter6)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return parameter6_ != NULL ? *parameter6_ : *default_instance().parameter6_;
#else
  return parameter6_ != NULL ? *parameter6_ : *default_instance_->parameter6_;
#endif
}
inline ::to::SensorReadings* BGEParameters::mutable_parameter6() {
  
  if (parameter6_ == NULL) {
    parameter6_ = new ::to::SensorReadings;
  }
  // @@protoc_insertion_point(field_mutable:to.BGEParameters.parameter6)
  return parameter6_;
}
inline ::to::SensorReadings* BGEParameters::release_parameter6() {
  // @@protoc_insertion_point(field_release:to.BGEParameters.parameter6)
  
  ::to::SensorReadings* temp = parameter6_;
  parameter6_ = NULL;
  return temp;
}
inline void BGEParameters::set_allocated_parameter6(::to::SensorReadings* parameter6) {
  delete parameter6_;
  parameter6_ = parameter6;
  if (parameter6) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:to.BGEParameters.parameter6)
}

// optional int32 parameter7 = 8;
inline void BGEParameters::clear_parameter7() {
  parameter7_ = 0;
}
inline ::google::protobuf::int32 BGEParameters::parameter7() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter7)
  return parameter7_;
}
inline void BGEParameters::set_parameter7(::google::protobuf::int32 value) {
  
  parameter7_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter7)
}

// optional bool parameter8 = 9;
inline void BGEParameters::clear_parameter8() {
  parameter8_ = false;
}
inline bool BGEParameters::parameter8() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter8)
  return parameter8_;
}
inline void BGEParameters::set_parameter8(bool value) {
  
  parameter8_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter8)
}

// optional double parameter9 = 10;
inline void BGEParameters::clear_parameter9() {
  parameter9_ = 0;
}
inline double BGEParameters::parameter9() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter9)
  return parameter9_;
}
inline void BGEParameters::set_parameter9(double value) {
  
  parameter9_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter9)
}

// optional int32 parameter10 = 11;
inline void BGEParameters::clear_parameter10() {
  parameter10_ = 0;
}
inline ::google::protobuf::int32 BGEParameters::parameter10() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter10)
  return parameter10_;
}
inline void BGEParameters::set_parameter10(::google::protobuf::int32 value) {
  
  parameter10_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter10)
}

// optional double parameter11 = 12;
inline void BGEParameters::clear_parameter11() {
  parameter11_ = 0;
}
inline double BGEParameters::parameter11() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter11)
  return parameter11_;
}
inline void BGEParameters::set_parameter11(double value) {
  
  parameter11_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter11)
}

// optional double parameter12 = 13;
inline void BGEParameters::clear_parameter12() {
  parameter12_ = 0;
}
inline double BGEParameters::parameter12() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter12)
  return parameter12_;
}
inline void BGEParameters::set_parameter12(double value) {
  
  parameter12_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter12)
}

// optional double parameter13 = 14;
inline void BGEParameters::clear_parameter13() {
  parameter13_ = 0;
}
inline double BGEParameters::parameter13() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter13)
  return parameter13_;
}
inline void BGEParameters::set_parameter13(double value) {
  
  parameter13_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter13)
}

// optional double parameter14 = 15;
inline void BGEParameters::clear_parameter14() {
  parameter14_ = 0;
}
inline double BGEParameters::parameter14() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter14)
  return parameter14_;
}
inline void BGEParameters::set_parameter14(double value) {
  
  parameter14_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter14)
}

// optional bool parameter15 = 16;
inline void BGEParameters::clear_parameter15() {
  parameter15_ = false;
}
inline bool BGEParameters::parameter15() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter15)
  return parameter15_;
}
inline void BGEParameters::set_parameter15(bool value) {
  
  parameter15_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter15)
}

// optional bool parameter16 = 17;
inline void BGEParameters::clear_parameter16() {
  parameter16_ = false;
}
inline bool BGEParameters::parameter16() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter16)
  return parameter16_;
}
inline void BGEParameters::set_parameter16(bool value) {
  
  parameter16_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter16)
}

// optional int32 count = 18;
inline void BGEParameters::clear_count() {
  count_ = 0;
}
inline ::google::protobuf::int32 BGEParameters::count() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.count)
  return count_;
}
inline void BGEParameters::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.count)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bge_5fparameters_2eproto__INCLUDED
