// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bge_parameters.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "bge_parameters.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace to {

void protobuf_ShutdownFile_bge_5fparameters_2eproto() {
  delete BGEParameters::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_bge_5fparameters_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_bge_5fparameters_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_bge_5fparameters_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::to::protobuf_AddDesc_sensor_5freadings_2eproto();
  BGEParameters::default_instance_ = new BGEParameters();
  BGEParameters::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_bge_5fparameters_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_bge_5fparameters_2eproto_once_);
void protobuf_AddDesc_bge_5fparameters_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_bge_5fparameters_2eproto_once_,
                 &protobuf_AddDesc_bge_5fparameters_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_bge_5fparameters_2eproto {
  StaticDescriptorInitializer_bge_5fparameters_2eproto() {
    protobuf_AddDesc_bge_5fparameters_2eproto();
  }
} static_descriptor_initializer_bge_5fparameters_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BGEParameters::kParameter0FieldNumber;
const int BGEParameters::kParameter1FieldNumber;
const int BGEParameters::kParameter2FieldNumber;
const int BGEParameters::kParameter3FieldNumber;
const int BGEParameters::kParameter4FieldNumber;
const int BGEParameters::kParameter5FieldNumber;
const int BGEParameters::kParameter6FieldNumber;
const int BGEParameters::kParameter7FieldNumber;
const int BGEParameters::kParameter8FieldNumber;
const int BGEParameters::kParameter9FieldNumber;
const int BGEParameters::kParameter10FieldNumber;
const int BGEParameters::kParameter11FieldNumber;
const int BGEParameters::kParameter12FieldNumber;
const int BGEParameters::kParameter13FieldNumber;
const int BGEParameters::kParameter14FieldNumber;
const int BGEParameters::kParameter15FieldNumber;
const int BGEParameters::kParameter16FieldNumber;
const int BGEParameters::kCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BGEParameters::BGEParameters()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:to.BGEParameters)
}

void BGEParameters::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  parameter6_ = const_cast< ::to::SensorReadings*>(
      ::to::SensorReadings::internal_default_instance());
#else
  parameter6_ = const_cast< ::to::SensorReadings*>(&::to::SensorReadings::default_instance());
#endif
}

BGEParameters::BGEParameters(const BGEParameters& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:to.BGEParameters)
}

void BGEParameters::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  parameter0_ = 0;
  parameter1_ = 0;
  parameter2_ = 0;
  parameter3_ = 0;
  parameter4_ = false;
  parameter5_ = 0;
  parameter6_ = NULL;
  parameter7_ = 0;
  parameter8_ = false;
  parameter9_ = 0;
  parameter10_ = 0;
  parameter11_ = 0;
  parameter12_ = 0;
  parameter13_ = 0;
  parameter14_ = 0;
  parameter15_ = false;
  parameter16_ = false;
  count_ = 0;
}

BGEParameters::~BGEParameters() {
  // @@protoc_insertion_point(destructor:to.BGEParameters)
  SharedDtor();
}

void BGEParameters::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete parameter6_;
  }
}

void BGEParameters::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BGEParameters& BGEParameters::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_bge_5fparameters_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_bge_5fparameters_2eproto();
#endif
  return *default_instance_;
}

BGEParameters* BGEParameters::default_instance_ = NULL;

BGEParameters* BGEParameters::New(::google::protobuf::Arena* arena) const {
  BGEParameters* n = new BGEParameters;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BGEParameters::Clear() {
// @@protoc_insertion_point(message_clear_start:to.BGEParameters)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(BGEParameters, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<BGEParameters*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(parameter0_, parameter3_);
  ZR_(parameter5_, parameter7_);
  parameter4_ = false;
  if (GetArenaNoVirtual() == NULL && parameter6_ != NULL) delete parameter6_;
  parameter6_ = NULL;
  ZR_(parameter9_, parameter10_);
  ZR_(parameter8_, parameter15_);
  ZR_(parameter11_, parameter14_);
  parameter16_ = false;
  count_ = 0;

#undef ZR_HELPER_
#undef ZR_

}

bool BGEParameters::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:to.BGEParameters)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double parameter0 = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter0_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_parameter1;
        break;
      }

      // optional double parameter1 = 2;
      case 2: {
        if (tag == 17) {
         parse_parameter1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_parameter2;
        break;
      }

      // optional float parameter2 = 3;
      case 3: {
        if (tag == 29) {
         parse_parameter2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &parameter2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_parameter3;
        break;
      }

      // optional float parameter3 = 4;
      case 4: {
        if (tag == 37) {
         parse_parameter3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &parameter3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_parameter4;
        break;
      }

      // optional bool parameter4 = 5;
      case 5: {
        if (tag == 40) {
         parse_parameter4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &parameter4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_parameter5;
        break;
      }

      // optional int32 parameter5 = 6;
      case 6: {
        if (tag == 48) {
         parse_parameter5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &parameter5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_parameter6;
        break;
      }

      // optional .to.SensorReadings parameter6 = 7;
      case 7: {
        if (tag == 58) {
         parse_parameter6:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_parameter6()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_parameter7;
        break;
      }

      // optional int32 parameter7 = 8;
      case 8: {
        if (tag == 64) {
         parse_parameter7:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &parameter7_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_parameter8;
        break;
      }

      // optional bool parameter8 = 9;
      case 9: {
        if (tag == 72) {
         parse_parameter8:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &parameter8_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_parameter9;
        break;
      }

      // optional double parameter9 = 10;
      case 10: {
        if (tag == 81) {
         parse_parameter9:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter9_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_parameter10;
        break;
      }

      // optional int32 parameter10 = 11;
      case 11: {
        if (tag == 88) {
         parse_parameter10:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &parameter10_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(97)) goto parse_parameter11;
        break;
      }

      // optional double parameter11 = 12;
      case 12: {
        if (tag == 97) {
         parse_parameter11:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter11_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(105)) goto parse_parameter12;
        break;
      }

      // optional double parameter12 = 13;
      case 13: {
        if (tag == 105) {
         parse_parameter12:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter12_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(113)) goto parse_parameter13;
        break;
      }

      // optional double parameter13 = 14;
      case 14: {
        if (tag == 113) {
         parse_parameter13:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter13_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(121)) goto parse_parameter14;
        break;
      }

      // optional double parameter14 = 15;
      case 15: {
        if (tag == 121) {
         parse_parameter14:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &parameter14_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_parameter15;
        break;
      }

      // optional bool parameter15 = 16;
      case 16: {
        if (tag == 128) {
         parse_parameter15:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &parameter15_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(136)) goto parse_parameter16;
        break;
      }

      // optional bool parameter16 = 17;
      case 17: {
        if (tag == 136) {
         parse_parameter16:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &parameter16_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(144)) goto parse_count;
        break;
      }

      // optional int32 count = 18;
      case 18: {
        if (tag == 144) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:to.BGEParameters)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:to.BGEParameters)
  return false;
#undef DO_
}

void BGEParameters::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:to.BGEParameters)
  // optional double parameter0 = 1;
  if (this->parameter0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->parameter0(), output);
  }

  // optional double parameter1 = 2;
  if (this->parameter1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->parameter1(), output);
  }

  // optional float parameter2 = 3;
  if (this->parameter2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->parameter2(), output);
  }

  // optional float parameter3 = 4;
  if (this->parameter3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->parameter3(), output);
  }

  // optional bool parameter4 = 5;
  if (this->parameter4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->parameter4(), output);
  }

  // optional int32 parameter5 = 6;
  if (this->parameter5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->parameter5(), output);
  }

  // optional .to.SensorReadings parameter6 = 7;
  if (this->has_parameter6()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      7, *this->parameter6_, output);
  }

  // optional int32 parameter7 = 8;
  if (this->parameter7() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->parameter7(), output);
  }

  // optional bool parameter8 = 9;
  if (this->parameter8() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->parameter8(), output);
  }

  // optional double parameter9 = 10;
  if (this->parameter9() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->parameter9(), output);
  }

  // optional int32 parameter10 = 11;
  if (this->parameter10() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->parameter10(), output);
  }

  // optional double parameter11 = 12;
  if (this->parameter11() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->parameter11(), output);
  }

  // optional double parameter12 = 13;
  if (this->parameter12() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->parameter12(), output);
  }

  // optional double parameter13 = 14;
  if (this->parameter13() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(14, this->parameter13(), output);
  }

  // optional double parameter14 = 15;
  if (this->parameter14() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(15, this->parameter14(), output);
  }

  // optional bool parameter15 = 16;
  if (this->parameter15() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(16, this->parameter15(), output);
  }

  // optional bool parameter16 = 17;
  if (this->parameter16() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(17, this->parameter16(), output);
  }

  // optional int32 count = 18;
  if (this->count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(18, this->count(), output);
  }

  // @@protoc_insertion_point(serialize_end:to.BGEParameters)
}

int BGEParameters::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:to.BGEParameters)
  int total_size = 0;

  // optional double parameter0 = 1;
  if (this->parameter0() != 0) {
    total_size += 1 + 8;
  }

  // optional double parameter1 = 2;
  if (this->parameter1() != 0) {
    total_size += 1 + 8;
  }

  // optional float parameter2 = 3;
  if (this->parameter2() != 0) {
    total_size += 1 + 4;
  }

  // optional float parameter3 = 4;
  if (this->parameter3() != 0) {
    total_size += 1 + 4;
  }

  // optional bool parameter4 = 5;
  if (this->parameter4() != 0) {
    total_size += 1 + 1;
  }

  // optional int32 parameter5 = 6;
  if (this->parameter5() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->parameter5());
  }

  // optional .to.SensorReadings parameter6 = 7;
  if (this->has_parameter6()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->parameter6_);
  }

  // optional int32 parameter7 = 8;
  if (this->parameter7() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->parameter7());
  }

  // optional bool parameter8 = 9;
  if (this->parameter8() != 0) {
    total_size += 1 + 1;
  }

  // optional double parameter9 = 10;
  if (this->parameter9() != 0) {
    total_size += 1 + 8;
  }

  // optional int32 parameter10 = 11;
  if (this->parameter10() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->parameter10());
  }

  // optional double parameter11 = 12;
  if (this->parameter11() != 0) {
    total_size += 1 + 8;
  }

  // optional double parameter12 = 13;
  if (this->parameter12() != 0) {
    total_size += 1 + 8;
  }

  // optional double parameter13 = 14;
  if (this->parameter13() != 0) {
    total_size += 1 + 8;
  }

  // optional double parameter14 = 15;
  if (this->parameter14() != 0) {
    total_size += 1 + 8;
  }

  // optional bool parameter15 = 16;
  if (this->parameter15() != 0) {
    total_size += 2 + 1;
  }

  // optional bool parameter16 = 17;
  if (this->parameter16() != 0) {
    total_size += 2 + 1;
  }

  // optional int32 count = 18;
  if (this->count() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->count());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BGEParameters::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BGEParameters*>(&from));
}

void BGEParameters::MergeFrom(const BGEParameters& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:to.BGEParameters)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.parameter0() != 0) {
    set_parameter0(from.parameter0());
  }
  if (from.parameter1() != 0) {
    set_parameter1(from.parameter1());
  }
  if (from.parameter2() != 0) {
    set_parameter2(from.parameter2());
  }
  if (from.parameter3() != 0) {
    set_parameter3(from.parameter3());
  }
  if (from.parameter4() != 0) {
    set_parameter4(from.parameter4());
  }
  if (from.parameter5() != 0) {
    set_parameter5(from.parameter5());
  }
  if (from.has_parameter6()) {
    mutable_parameter6()->::to::SensorReadings::MergeFrom(from.parameter6());
  }
  if (from.parameter7() != 0) {
    set_parameter7(from.parameter7());
  }
  if (from.parameter8() != 0) {
    set_parameter8(from.parameter8());
  }
  if (from.parameter9() != 0) {
    set_parameter9(from.parameter9());
  }
  if (from.parameter10() != 0) {
    set_parameter10(from.parameter10());
  }
  if (from.parameter11() != 0) {
    set_parameter11(from.parameter11());
  }
  if (from.parameter12() != 0) {
    set_parameter12(from.parameter12());
  }
  if (from.parameter13() != 0) {
    set_parameter13(from.parameter13());
  }
  if (from.parameter14() != 0) {
    set_parameter14(from.parameter14());
  }
  if (from.parameter15() != 0) {
    set_parameter15(from.parameter15());
  }
  if (from.parameter16() != 0) {
    set_parameter16(from.parameter16());
  }
  if (from.count() != 0) {
    set_count(from.count());
  }
}

void BGEParameters::CopyFrom(const BGEParameters& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:to.BGEParameters)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BGEParameters::IsInitialized() const {

  return true;
}

void BGEParameters::Swap(BGEParameters* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BGEParameters::InternalSwap(BGEParameters* other) {
  std::swap(parameter0_, other->parameter0_);
  std::swap(parameter1_, other->parameter1_);
  std::swap(parameter2_, other->parameter2_);
  std::swap(parameter3_, other->parameter3_);
  std::swap(parameter4_, other->parameter4_);
  std::swap(parameter5_, other->parameter5_);
  std::swap(parameter6_, other->parameter6_);
  std::swap(parameter7_, other->parameter7_);
  std::swap(parameter8_, other->parameter8_);
  std::swap(parameter9_, other->parameter9_);
  std::swap(parameter10_, other->parameter10_);
  std::swap(parameter11_, other->parameter11_);
  std::swap(parameter12_, other->parameter12_);
  std::swap(parameter13_, other->parameter13_);
  std::swap(parameter14_, other->parameter14_);
  std::swap(parameter15_, other->parameter15_);
  std::swap(parameter16_, other->parameter16_);
  std::swap(count_, other->count_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string BGEParameters::GetTypeName() const {
  return "to.BGEParameters";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BGEParameters

// optional double parameter0 = 1;
void BGEParameters::clear_parameter0() {
  parameter0_ = 0;
}
 double BGEParameters::parameter0() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter0)
  return parameter0_;
}
 void BGEParameters::set_parameter0(double value) {
  
  parameter0_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter0)
}

// optional double parameter1 = 2;
void BGEParameters::clear_parameter1() {
  parameter1_ = 0;
}
 double BGEParameters::parameter1() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter1)
  return parameter1_;
}
 void BGEParameters::set_parameter1(double value) {
  
  parameter1_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter1)
}

// optional float parameter2 = 3;
void BGEParameters::clear_parameter2() {
  parameter2_ = 0;
}
 float BGEParameters::parameter2() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter2)
  return parameter2_;
}
 void BGEParameters::set_parameter2(float value) {
  
  parameter2_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter2)
}

// optional float parameter3 = 4;
void BGEParameters::clear_parameter3() {
  parameter3_ = 0;
}
 float BGEParameters::parameter3() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter3)
  return parameter3_;
}
 void BGEParameters::set_parameter3(float value) {
  
  parameter3_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter3)
}

// optional bool parameter4 = 5;
void BGEParameters::clear_parameter4() {
  parameter4_ = false;
}
 bool BGEParameters::parameter4() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter4)
  return parameter4_;
}
 void BGEParameters::set_parameter4(bool value) {
  
  parameter4_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter4)
}

// optional int32 parameter5 = 6;
void BGEParameters::clear_parameter5() {
  parameter5_ = 0;
}
 ::google::protobuf::int32 BGEParameters::parameter5() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter5)
  return parameter5_;
}
 void BGEParameters::set_parameter5(::google::protobuf::int32 value) {
  
  parameter5_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter5)
}

// optional .to.SensorReadings parameter6 = 7;
bool BGEParameters::has_parameter6() const {
  return !_is_default_instance_ && parameter6_ != NULL;
}
void BGEParameters::clear_parameter6() {
  if (GetArenaNoVirtual() == NULL && parameter6_ != NULL) delete parameter6_;
  parameter6_ = NULL;
}
const ::to::SensorReadings& BGEParameters::parameter6() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter6)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return parameter6_ != NULL ? *parameter6_ : *default_instance().parameter6_;
#else
  return parameter6_ != NULL ? *parameter6_ : *default_instance_->parameter6_;
#endif
}
::to::SensorReadings* BGEParameters::mutable_parameter6() {
  
  if (parameter6_ == NULL) {
    parameter6_ = new ::to::SensorReadings;
  }
  // @@protoc_insertion_point(field_mutable:to.BGEParameters.parameter6)
  return parameter6_;
}
::to::SensorReadings* BGEParameters::release_parameter6() {
  // @@protoc_insertion_point(field_release:to.BGEParameters.parameter6)
  
  ::to::SensorReadings* temp = parameter6_;
  parameter6_ = NULL;
  return temp;
}
void BGEParameters::set_allocated_parameter6(::to::SensorReadings* parameter6) {
  delete parameter6_;
  parameter6_ = parameter6;
  if (parameter6) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:to.BGEParameters.parameter6)
}

// optional int32 parameter7 = 8;
void BGEParameters::clear_parameter7() {
  parameter7_ = 0;
}
 ::google::protobuf::int32 BGEParameters::parameter7() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter7)
  return parameter7_;
}
 void BGEParameters::set_parameter7(::google::protobuf::int32 value) {
  
  parameter7_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter7)
}

// optional bool parameter8 = 9;
void BGEParameters::clear_parameter8() {
  parameter8_ = false;
}
 bool BGEParameters::parameter8() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter8)
  return parameter8_;
}
 void BGEParameters::set_parameter8(bool value) {
  
  parameter8_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter8)
}

// optional double parameter9 = 10;
void BGEParameters::clear_parameter9() {
  parameter9_ = 0;
}
 double BGEParameters::parameter9() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter9)
  return parameter9_;
}
 void BGEParameters::set_parameter9(double value) {
  
  parameter9_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter9)
}

// optional int32 parameter10 = 11;
void BGEParameters::clear_parameter10() {
  parameter10_ = 0;
}
 ::google::protobuf::int32 BGEParameters::parameter10() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter10)
  return parameter10_;
}
 void BGEParameters::set_parameter10(::google::protobuf::int32 value) {
  
  parameter10_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter10)
}

// optional double parameter11 = 12;
void BGEParameters::clear_parameter11() {
  parameter11_ = 0;
}
 double BGEParameters::parameter11() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter11)
  return parameter11_;
}
 void BGEParameters::set_parameter11(double value) {
  
  parameter11_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter11)
}

// optional double parameter12 = 13;
void BGEParameters::clear_parameter12() {
  parameter12_ = 0;
}
 double BGEParameters::parameter12() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter12)
  return parameter12_;
}
 void BGEParameters::set_parameter12(double value) {
  
  parameter12_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter12)
}

// optional double parameter13 = 14;
void BGEParameters::clear_parameter13() {
  parameter13_ = 0;
}
 double BGEParameters::parameter13() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter13)
  return parameter13_;
}
 void BGEParameters::set_parameter13(double value) {
  
  parameter13_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter13)
}

// optional double parameter14 = 15;
void BGEParameters::clear_parameter14() {
  parameter14_ = 0;
}
 double BGEParameters::parameter14() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter14)
  return parameter14_;
}
 void BGEParameters::set_parameter14(double value) {
  
  parameter14_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter14)
}

// optional bool parameter15 = 16;
void BGEParameters::clear_parameter15() {
  parameter15_ = false;
}
 bool BGEParameters::parameter15() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter15)
  return parameter15_;
}
 void BGEParameters::set_parameter15(bool value) {
  
  parameter15_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter15)
}

// optional bool parameter16 = 17;
void BGEParameters::clear_parameter16() {
  parameter16_ = false;
}
 bool BGEParameters::parameter16() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.parameter16)
  return parameter16_;
}
 void BGEParameters::set_parameter16(bool value) {
  
  parameter16_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.parameter16)
}

// optional int32 count = 18;
void BGEParameters::clear_count() {
  count_ = 0;
}
 ::google::protobuf::int32 BGEParameters::count() const {
  // @@protoc_insertion_point(field_get:to.BGEParameters.count)
  return count_;
}
 void BGEParameters::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:to.BGEParameters.count)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)
