// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc_bge_response.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "calc_bge_response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace to {

void protobuf_ShutdownFile_calc_5fbge_5fresponse_2eproto() {
  delete CalculateBGEResponse::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_calc_5fbge_5fresponse_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_calc_5fbge_5fresponse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_calc_5fbge_5fresponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::to::protobuf_AddDesc_sensor_5freadings_2eproto();
  ::to::protobuf_AddDesc_bge_5fparameters_2eproto();
  CalculateBGEResponse::default_instance_ = new CalculateBGEResponse();
  CalculateBGEResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_calc_5fbge_5fresponse_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_calc_5fbge_5fresponse_2eproto_once_);
void protobuf_AddDesc_calc_5fbge_5fresponse_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_calc_5fbge_5fresponse_2eproto_once_,
                 &protobuf_AddDesc_calc_5fbge_5fresponse_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_calc_5fbge_5fresponse_2eproto {
  StaticDescriptorInitializer_calc_5fbge_5fresponse_2eproto() {
    protobuf_AddDesc_calc_5fbge_5fresponse_2eproto();
  }
} static_descriptor_initializer_calc_5fbge_5fresponse_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CalculateBGEResponse::kErrorCodeFieldNumber;
const int CalculateBGEResponse::kErrorMessageFieldNumber;
const int CalculateBGEResponse::kSensorReadingsFieldNumber;
const int CalculateBGEResponse::kParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CalculateBGEResponse::CalculateBGEResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:to.CalculateBGEResponse)
}

void CalculateBGEResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  params_ = const_cast< ::to::BGEParameters*>(
      ::to::BGEParameters::internal_default_instance());
#else
  params_ = const_cast< ::to::BGEParameters*>(&::to::BGEParameters::default_instance());
#endif
}

CalculateBGEResponse::CalculateBGEResponse(const CalculateBGEResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:to.CalculateBGEResponse)
}

void CalculateBGEResponse::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  errorcode_ = 0;
  errormessage_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  params_ = NULL;
}

CalculateBGEResponse::~CalculateBGEResponse() {
  // @@protoc_insertion_point(destructor:to.CalculateBGEResponse)
  SharedDtor();
}

void CalculateBGEResponse::SharedDtor() {
  errormessage_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete params_;
  }
}

void CalculateBGEResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CalculateBGEResponse& CalculateBGEResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_calc_5fbge_5fresponse_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_calc_5fbge_5fresponse_2eproto();
#endif
  return *default_instance_;
}

CalculateBGEResponse* CalculateBGEResponse::default_instance_ = NULL;

CalculateBGEResponse* CalculateBGEResponse::New(::google::protobuf::Arena* arena) const {
  CalculateBGEResponse* n = new CalculateBGEResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CalculateBGEResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:to.CalculateBGEResponse)
  errorcode_ = 0;
  errormessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && params_ != NULL) delete params_;
  params_ = NULL;
  sensorreadings_.Clear();
}

bool CalculateBGEResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:to.CalculateBGEResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 errorCode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &errorcode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_errorMessage;
        break;
      }

      // optional string errorMessage = 2;
      case 2: {
        if (tag == 18) {
         parse_errorMessage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_errormessage()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->errormessage().data(), this->errormessage().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "to.CalculateBGEResponse.errorMessage"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_sensorReadings;
        break;
      }

      // repeated .to.SensorReadings sensorReadings = 3;
      case 3: {
        if (tag == 26) {
         parse_sensorReadings:
          DO_(input->IncrementRecursionDepth());
         parse_loop_sensorReadings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_sensorreadings()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_sensorReadings;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(34)) goto parse_params;
        break;
      }

      // optional .to.BGEParameters params = 4;
      case 4: {
        if (tag == 34) {
         parse_params:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_params()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:to.CalculateBGEResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:to.CalculateBGEResponse)
  return false;
#undef DO_
}

void CalculateBGEResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:to.CalculateBGEResponse)
  // optional int32 errorCode = 1;
  if (this->errorcode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->errorcode(), output);
  }

  // optional string errorMessage = 2;
  if (this->errormessage().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->errormessage().data(), this->errormessage().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "to.CalculateBGEResponse.errorMessage");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->errormessage(), output);
  }

  // repeated .to.SensorReadings sensorReadings = 3;
  for (unsigned int i = 0, n = this->sensorreadings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->sensorreadings(i), output);
  }

  // optional .to.BGEParameters params = 4;
  if (this->has_params()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, *this->params_, output);
  }

  // @@protoc_insertion_point(serialize_end:to.CalculateBGEResponse)
}

int CalculateBGEResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:to.CalculateBGEResponse)
  int total_size = 0;

  // optional int32 errorCode = 1;
  if (this->errorcode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->errorcode());
  }

  // optional string errorMessage = 2;
  if (this->errormessage().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->errormessage());
  }

  // optional .to.BGEParameters params = 4;
  if (this->has_params()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->params_);
  }

  // repeated .to.SensorReadings sensorReadings = 3;
  total_size += 1 * this->sensorreadings_size();
  for (int i = 0; i < this->sensorreadings_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->sensorreadings(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CalculateBGEResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CalculateBGEResponse*>(&from));
}

void CalculateBGEResponse::MergeFrom(const CalculateBGEResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:to.CalculateBGEResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  sensorreadings_.MergeFrom(from.sensorreadings_);
  if (from.errorcode() != 0) {
    set_errorcode(from.errorcode());
  }
  if (from.errormessage().size() > 0) {

    errormessage_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.errormessage_);
  }
  if (from.has_params()) {
    mutable_params()->::to::BGEParameters::MergeFrom(from.params());
  }
}

void CalculateBGEResponse::CopyFrom(const CalculateBGEResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:to.CalculateBGEResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CalculateBGEResponse::IsInitialized() const {

  return true;
}

void CalculateBGEResponse::Swap(CalculateBGEResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CalculateBGEResponse::InternalSwap(CalculateBGEResponse* other) {
  std::swap(errorcode_, other->errorcode_);
  errormessage_.Swap(&other->errormessage_);
  sensorreadings_.UnsafeArenaSwap(&other->sensorreadings_);
  std::swap(params_, other->params_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string CalculateBGEResponse::GetTypeName() const {
  return "to.CalculateBGEResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CalculateBGEResponse

// optional int32 errorCode = 1;
void CalculateBGEResponse::clear_errorcode() {
  errorcode_ = 0;
}
 ::google::protobuf::int32 CalculateBGEResponse::errorcode() const {
  // @@protoc_insertion_point(field_get:to.CalculateBGEResponse.errorCode)
  return errorcode_;
}
 void CalculateBGEResponse::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:to.CalculateBGEResponse.errorCode)
}

// optional string errorMessage = 2;
void CalculateBGEResponse::clear_errormessage() {
  errormessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CalculateBGEResponse::errormessage() const {
  // @@protoc_insertion_point(field_get:to.CalculateBGEResponse.errorMessage)
  return errormessage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CalculateBGEResponse::set_errormessage(const ::std::string& value) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:to.CalculateBGEResponse.errorMessage)
}
 void CalculateBGEResponse::set_errormessage(const char* value) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:to.CalculateBGEResponse.errorMessage)
}
 void CalculateBGEResponse::set_errormessage(const char* value, size_t size) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:to.CalculateBGEResponse.errorMessage)
}
 ::std::string* CalculateBGEResponse::mutable_errormessage() {
  
  // @@protoc_insertion_point(field_mutable:to.CalculateBGEResponse.errorMessage)
  return errormessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CalculateBGEResponse::release_errormessage() {
  // @@protoc_insertion_point(field_release:to.CalculateBGEResponse.errorMessage)
  
  return errormessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CalculateBGEResponse::set_allocated_errormessage(::std::string* errormessage) {
  if (errormessage != NULL) {
    
  } else {
    
  }
  errormessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errormessage);
  // @@protoc_insertion_point(field_set_allocated:to.CalculateBGEResponse.errorMessage)
}

// repeated .to.SensorReadings sensorReadings = 3;
int CalculateBGEResponse::sensorreadings_size() const {
  return sensorreadings_.size();
}
void CalculateBGEResponse::clear_sensorreadings() {
  sensorreadings_.Clear();
}
const ::to::SensorReadings& CalculateBGEResponse::sensorreadings(int index) const {
  // @@protoc_insertion_point(field_get:to.CalculateBGEResponse.sensorReadings)
  return sensorreadings_.Get(index);
}
::to::SensorReadings* CalculateBGEResponse::mutable_sensorreadings(int index) {
  // @@protoc_insertion_point(field_mutable:to.CalculateBGEResponse.sensorReadings)
  return sensorreadings_.Mutable(index);
}
::to::SensorReadings* CalculateBGEResponse::add_sensorreadings() {
  // @@protoc_insertion_point(field_add:to.CalculateBGEResponse.sensorReadings)
  return sensorreadings_.Add();
}
::google::protobuf::RepeatedPtrField< ::to::SensorReadings >*
CalculateBGEResponse::mutable_sensorreadings() {
  // @@protoc_insertion_point(field_mutable_list:to.CalculateBGEResponse.sensorReadings)
  return &sensorreadings_;
}
const ::google::protobuf::RepeatedPtrField< ::to::SensorReadings >&
CalculateBGEResponse::sensorreadings() const {
  // @@protoc_insertion_point(field_list:to.CalculateBGEResponse.sensorReadings)
  return sensorreadings_;
}

// optional .to.BGEParameters params = 4;
bool CalculateBGEResponse::has_params() const {
  return !_is_default_instance_ && params_ != NULL;
}
void CalculateBGEResponse::clear_params() {
  if (GetArenaNoVirtual() == NULL && params_ != NULL) delete params_;
  params_ = NULL;
}
const ::to::BGEParameters& CalculateBGEResponse::params() const {
  // @@protoc_insertion_point(field_get:to.CalculateBGEResponse.params)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return params_ != NULL ? *params_ : *default_instance().params_;
#else
  return params_ != NULL ? *params_ : *default_instance_->params_;
#endif
}
::to::BGEParameters* CalculateBGEResponse::mutable_params() {
  
  if (params_ == NULL) {
    params_ = new ::to::BGEParameters;
  }
  // @@protoc_insertion_point(field_mutable:to.CalculateBGEResponse.params)
  return params_;
}
::to::BGEParameters* CalculateBGEResponse::release_params() {
  // @@protoc_insertion_point(field_release:to.CalculateBGEResponse.params)
  
  ::to::BGEParameters* temp = params_;
  params_ = NULL;
  return temp;
}
void CalculateBGEResponse::set_allocated_params(::to::BGEParameters* params) {
  delete params_;
  params_ = params;
  if (params) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:to.CalculateBGEResponse.params)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)
