// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: check_for_early_injection_response.proto

#ifndef PROTOBUF_check_5ffor_5fearly_5finjection_5fresponse_2eproto__INCLUDED
#define PROTOBUF_check_5ffor_5fearly_5finjection_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "sensor_readings.pb.h"
// @@protoc_insertion_point(includes)

namespace to {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_check_5ffor_5fearly_5finjection_5fresponse_2eproto();
void protobuf_AssignDesc_check_5ffor_5fearly_5finjection_5fresponse_2eproto();
void protobuf_ShutdownFile_check_5ffor_5fearly_5finjection_5fresponse_2eproto();

class CheckForEarlyInjectionResponse;

// ===================================================================

class CheckForEarlyInjectionResponse : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:to.CheckForEarlyInjectionResponse) */ {
 public:
  CheckForEarlyInjectionResponse();
  virtual ~CheckForEarlyInjectionResponse();

  CheckForEarlyInjectionResponse(const CheckForEarlyInjectionResponse& from);

  inline CheckForEarlyInjectionResponse& operator=(const CheckForEarlyInjectionResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const CheckForEarlyInjectionResponse& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CheckForEarlyInjectionResponse* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CheckForEarlyInjectionResponse* other);

  // implements Message ----------------------------------------------

  inline CheckForEarlyInjectionResponse* New() const { return New(NULL); }

  CheckForEarlyInjectionResponse* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CheckForEarlyInjectionResponse& from);
  void MergeFrom(const CheckForEarlyInjectionResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CheckForEarlyInjectionResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 errorCode = 1;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // optional string errorMessage = 2;
  void clear_errormessage();
  static const int kErrorMessageFieldNumber = 2;
  const ::std::string& errormessage() const;
  void set_errormessage(const ::std::string& value);
  void set_errormessage(const char* value);
  void set_errormessage(const char* value, size_t size);
  ::std::string* mutable_errormessage();
  ::std::string* release_errormessage();
  void set_allocated_errormessage(::std::string* errormessage);

  // optional int32 amReturnCode = 3;
  void clear_amreturncode();
  static const int kAmReturnCodeFieldNumber = 3;
  ::google::protobuf::int32 amreturncode() const;
  void set_amreturncode(::google::protobuf::int32 value);

  // optional .to.SensorReadings hematocritReadings = 4;
  bool has_hematocritreadings() const;
  void clear_hematocritreadings();
  static const int kHematocritReadingsFieldNumber = 4;
  const ::to::SensorReadings& hematocritreadings() const;
  ::to::SensorReadings* mutable_hematocritreadings();
  ::to::SensorReadings* release_hematocritreadings();
  void set_allocated_hematocritreadings(::to::SensorReadings* hematocritreadings);

  // @@protoc_insertion_point(class_scope:to.CheckForEarlyInjectionResponse)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr errormessage_;
  ::google::protobuf::int32 errorcode_;
  ::google::protobuf::int32 amreturncode_;
  ::to::SensorReadings* hematocritreadings_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_check_5ffor_5fearly_5finjection_5fresponse_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_check_5ffor_5fearly_5finjection_5fresponse_2eproto();
  #endif
  friend void protobuf_AssignDesc_check_5ffor_5fearly_5finjection_5fresponse_2eproto();
  friend void protobuf_ShutdownFile_check_5ffor_5fearly_5finjection_5fresponse_2eproto();

  void InitAsDefaultInstance();
  static CheckForEarlyInjectionResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CheckForEarlyInjectionResponse

// optional int32 errorCode = 1;
inline void CheckForEarlyInjectionResponse::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 CheckForEarlyInjectionResponse::errorcode() const {
  // @@protoc_insertion_point(field_get:to.CheckForEarlyInjectionResponse.errorCode)
  return errorcode_;
}
inline void CheckForEarlyInjectionResponse::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:to.CheckForEarlyInjectionResponse.errorCode)
}

// optional string errorMessage = 2;
inline void CheckForEarlyInjectionResponse::clear_errormessage() {
  errormessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CheckForEarlyInjectionResponse::errormessage() const {
  // @@protoc_insertion_point(field_get:to.CheckForEarlyInjectionResponse.errorMessage)
  return errormessage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CheckForEarlyInjectionResponse::set_errormessage(const ::std::string& value) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:to.CheckForEarlyInjectionResponse.errorMessage)
}
inline void CheckForEarlyInjectionResponse::set_errormessage(const char* value) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:to.CheckForEarlyInjectionResponse.errorMessage)
}
inline void CheckForEarlyInjectionResponse::set_errormessage(const char* value, size_t size) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:to.CheckForEarlyInjectionResponse.errorMessage)
}
inline ::std::string* CheckForEarlyInjectionResponse::mutable_errormessage() {
  
  // @@protoc_insertion_point(field_mutable:to.CheckForEarlyInjectionResponse.errorMessage)
  return errormessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CheckForEarlyInjectionResponse::release_errormessage() {
  // @@protoc_insertion_point(field_release:to.CheckForEarlyInjectionResponse.errorMessage)
  
  return errormessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CheckForEarlyInjectionResponse::set_allocated_errormessage(::std::string* errormessage) {
  if (errormessage != NULL) {
    
  } else {
    
  }
  errormessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errormessage);
  // @@protoc_insertion_point(field_set_allocated:to.CheckForEarlyInjectionResponse.errorMessage)
}

// optional int32 amReturnCode = 3;
inline void CheckForEarlyInjectionResponse::clear_amreturncode() {
  amreturncode_ = 0;
}
inline ::google::protobuf::int32 CheckForEarlyInjectionResponse::amreturncode() const {
  // @@protoc_insertion_point(field_get:to.CheckForEarlyInjectionResponse.amReturnCode)
  return amreturncode_;
}
inline void CheckForEarlyInjectionResponse::set_amreturncode(::google::protobuf::int32 value) {
  
  amreturncode_ = value;
  // @@protoc_insertion_point(field_set:to.CheckForEarlyInjectionResponse.amReturnCode)
}

// optional .to.SensorReadings hematocritReadings = 4;
inline bool CheckForEarlyInjectionResponse::has_hematocritreadings() const {
  return !_is_default_instance_ && hematocritreadings_ != NULL;
}
inline void CheckForEarlyInjectionResponse::clear_hematocritreadings() {
  if (GetArenaNoVirtual() == NULL && hematocritreadings_ != NULL) delete hematocritreadings_;
  hematocritreadings_ = NULL;
}
inline const ::to::SensorReadings& CheckForEarlyInjectionResponse::hematocritreadings() const {
  // @@protoc_insertion_point(field_get:to.CheckForEarlyInjectionResponse.hematocritReadings)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return hematocritreadings_ != NULL ? *hematocritreadings_ : *default_instance().hematocritreadings_;
#else
  return hematocritreadings_ != NULL ? *hematocritreadings_ : *default_instance_->hematocritreadings_;
#endif
}
inline ::to::SensorReadings* CheckForEarlyInjectionResponse::mutable_hematocritreadings() {
  
  if (hematocritreadings_ == NULL) {
    hematocritreadings_ = new ::to::SensorReadings;
  }
  // @@protoc_insertion_point(field_mutable:to.CheckForEarlyInjectionResponse.hematocritReadings)
  return hematocritreadings_;
}
inline ::to::SensorReadings* CheckForEarlyInjectionResponse::release_hematocritreadings() {
  // @@protoc_insertion_point(field_release:to.CheckForEarlyInjectionResponse.hematocritReadings)
  
  ::to::SensorReadings* temp = hematocritreadings_;
  hematocritreadings_ = NULL;
  return temp;
}
inline void CheckForEarlyInjectionResponse::set_allocated_hematocritreadings(::to::SensorReadings* hematocritreadings) {
  delete hematocritreadings_;
  hematocritreadings_ = hematocritreadings;
  if (hematocritreadings) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:to.CheckForEarlyInjectionResponse.hematocritReadings)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_check_5ffor_5fearly_5finjection_5fresponse_2eproto__INCLUDED
