// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: perform_realtime_qc_response.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "perform_realtime_qc_response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace to {

void protobuf_ShutdownFile_perform_5frealtime_5fqc_5fresponse_2eproto() {
  delete PerformRealTimeQCResponse::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::to::protobuf_AddDesc_sensor_5freadings_2eproto();
  PerformRealTimeQCResponse::default_instance_ = new PerformRealTimeQCResponse();
  PerformRealTimeQCResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_perform_5frealtime_5fqc_5fresponse_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto_once_);
void protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto_once_,
                 &protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_perform_5frealtime_5fqc_5fresponse_2eproto {
  StaticDescriptorInitializer_perform_5frealtime_5fqc_5fresponse_2eproto() {
    protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto();
  }
} static_descriptor_initializer_perform_5frealtime_5fqc_5fresponse_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PerformRealTimeQCResponse::kErrorCodeFieldNumber;
const int PerformRealTimeQCResponse::kErrorMessageFieldNumber;
const int PerformRealTimeQCResponse::kAmReturnCodeFieldNumber;
const int PerformRealTimeQCResponse::kTestReadingsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PerformRealTimeQCResponse::PerformRealTimeQCResponse()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:to.PerformRealTimeQCResponse)
}

void PerformRealTimeQCResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PerformRealTimeQCResponse::PerformRealTimeQCResponse(const PerformRealTimeQCResponse& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:to.PerformRealTimeQCResponse)
}

void PerformRealTimeQCResponse::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  errorcode_ = 0;
  errormessage_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  amreturncode_ = 0;
}

PerformRealTimeQCResponse::~PerformRealTimeQCResponse() {
  // @@protoc_insertion_point(destructor:to.PerformRealTimeQCResponse)
  SharedDtor();
}

void PerformRealTimeQCResponse::SharedDtor() {
  errormessage_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PerformRealTimeQCResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PerformRealTimeQCResponse& PerformRealTimeQCResponse::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_perform_5frealtime_5fqc_5fresponse_2eproto();
#endif
  return *default_instance_;
}

PerformRealTimeQCResponse* PerformRealTimeQCResponse::default_instance_ = NULL;

PerformRealTimeQCResponse* PerformRealTimeQCResponse::New(::google::protobuf::Arena* arena) const {
  PerformRealTimeQCResponse* n = new PerformRealTimeQCResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PerformRealTimeQCResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:to.PerformRealTimeQCResponse)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PerformRealTimeQCResponse, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PerformRealTimeQCResponse*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(errorcode_, amreturncode_);
  errormessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

  testreadings_.Clear();
}

bool PerformRealTimeQCResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:to.PerformRealTimeQCResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 errorCode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &errorcode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_errorMessage;
        break;
      }

      // optional string errorMessage = 2;
      case 2: {
        if (tag == 18) {
         parse_errorMessage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_errormessage()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->errormessage().data(), this->errormessage().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "to.PerformRealTimeQCResponse.errorMessage"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_amReturnCode;
        break;
      }

      // optional int32 amReturnCode = 3;
      case 3: {
        if (tag == 24) {
         parse_amReturnCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &amreturncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_testReadings;
        break;
      }

      // repeated .to.SensorReadings testReadings = 4;
      case 4: {
        if (tag == 34) {
         parse_testReadings:
          DO_(input->IncrementRecursionDepth());
         parse_loop_testReadings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_testreadings()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_testReadings;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:to.PerformRealTimeQCResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:to.PerformRealTimeQCResponse)
  return false;
#undef DO_
}

void PerformRealTimeQCResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:to.PerformRealTimeQCResponse)
  // optional int32 errorCode = 1;
  if (this->errorcode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->errorcode(), output);
  }

  // optional string errorMessage = 2;
  if (this->errormessage().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->errormessage().data(), this->errormessage().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "to.PerformRealTimeQCResponse.errorMessage");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->errormessage(), output);
  }

  // optional int32 amReturnCode = 3;
  if (this->amreturncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->amreturncode(), output);
  }

  // repeated .to.SensorReadings testReadings = 4;
  for (unsigned int i = 0, n = this->testreadings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->testreadings(i), output);
  }

  // @@protoc_insertion_point(serialize_end:to.PerformRealTimeQCResponse)
}

int PerformRealTimeQCResponse::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:to.PerformRealTimeQCResponse)
  int total_size = 0;

  // optional int32 errorCode = 1;
  if (this->errorcode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->errorcode());
  }

  // optional string errorMessage = 2;
  if (this->errormessage().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->errormessage());
  }

  // optional int32 amReturnCode = 3;
  if (this->amreturncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->amreturncode());
  }

  // repeated .to.SensorReadings testReadings = 4;
  total_size += 1 * this->testreadings_size();
  for (int i = 0; i < this->testreadings_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->testreadings(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PerformRealTimeQCResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PerformRealTimeQCResponse*>(&from));
}

void PerformRealTimeQCResponse::MergeFrom(const PerformRealTimeQCResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:to.PerformRealTimeQCResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  testreadings_.MergeFrom(from.testreadings_);
  if (from.errorcode() != 0) {
    set_errorcode(from.errorcode());
  }
  if (from.errormessage().size() > 0) {

    errormessage_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.errormessage_);
  }
  if (from.amreturncode() != 0) {
    set_amreturncode(from.amreturncode());
  }
}

void PerformRealTimeQCResponse::CopyFrom(const PerformRealTimeQCResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:to.PerformRealTimeQCResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PerformRealTimeQCResponse::IsInitialized() const {

  return true;
}

void PerformRealTimeQCResponse::Swap(PerformRealTimeQCResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PerformRealTimeQCResponse::InternalSwap(PerformRealTimeQCResponse* other) {
  std::swap(errorcode_, other->errorcode_);
  errormessage_.Swap(&other->errormessage_);
  std::swap(amreturncode_, other->amreturncode_);
  testreadings_.UnsafeArenaSwap(&other->testreadings_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string PerformRealTimeQCResponse::GetTypeName() const {
  return "to.PerformRealTimeQCResponse";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PerformRealTimeQCResponse

// optional int32 errorCode = 1;
void PerformRealTimeQCResponse::clear_errorcode() {
  errorcode_ = 0;
}
 ::google::protobuf::int32 PerformRealTimeQCResponse::errorcode() const {
  // @@protoc_insertion_point(field_get:to.PerformRealTimeQCResponse.errorCode)
  return errorcode_;
}
 void PerformRealTimeQCResponse::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:to.PerformRealTimeQCResponse.errorCode)
}

// optional string errorMessage = 2;
void PerformRealTimeQCResponse::clear_errormessage() {
  errormessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PerformRealTimeQCResponse::errormessage() const {
  // @@protoc_insertion_point(field_get:to.PerformRealTimeQCResponse.errorMessage)
  return errormessage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PerformRealTimeQCResponse::set_errormessage(const ::std::string& value) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:to.PerformRealTimeQCResponse.errorMessage)
}
 void PerformRealTimeQCResponse::set_errormessage(const char* value) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:to.PerformRealTimeQCResponse.errorMessage)
}
 void PerformRealTimeQCResponse::set_errormessage(const char* value, size_t size) {
  
  errormessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:to.PerformRealTimeQCResponse.errorMessage)
}
 ::std::string* PerformRealTimeQCResponse::mutable_errormessage() {
  
  // @@protoc_insertion_point(field_mutable:to.PerformRealTimeQCResponse.errorMessage)
  return errormessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PerformRealTimeQCResponse::release_errormessage() {
  // @@protoc_insertion_point(field_release:to.PerformRealTimeQCResponse.errorMessage)
  
  return errormessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PerformRealTimeQCResponse::set_allocated_errormessage(::std::string* errormessage) {
  if (errormessage != NULL) {
    
  } else {
    
  }
  errormessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errormessage);
  // @@protoc_insertion_point(field_set_allocated:to.PerformRealTimeQCResponse.errorMessage)
}

// optional int32 amReturnCode = 3;
void PerformRealTimeQCResponse::clear_amreturncode() {
  amreturncode_ = 0;
}
 ::google::protobuf::int32 PerformRealTimeQCResponse::amreturncode() const {
  // @@protoc_insertion_point(field_get:to.PerformRealTimeQCResponse.amReturnCode)
  return amreturncode_;
}
 void PerformRealTimeQCResponse::set_amreturncode(::google::protobuf::int32 value) {
  
  amreturncode_ = value;
  // @@protoc_insertion_point(field_set:to.PerformRealTimeQCResponse.amReturnCode)
}

// repeated .to.SensorReadings testReadings = 4;
int PerformRealTimeQCResponse::testreadings_size() const {
  return testreadings_.size();
}
void PerformRealTimeQCResponse::clear_testreadings() {
  testreadings_.Clear();
}
const ::to::SensorReadings& PerformRealTimeQCResponse::testreadings(int index) const {
  // @@protoc_insertion_point(field_get:to.PerformRealTimeQCResponse.testReadings)
  return testreadings_.Get(index);
}
::to::SensorReadings* PerformRealTimeQCResponse::mutable_testreadings(int index) {
  // @@protoc_insertion_point(field_mutable:to.PerformRealTimeQCResponse.testReadings)
  return testreadings_.Mutable(index);
}
::to::SensorReadings* PerformRealTimeQCResponse::add_testreadings() {
  // @@protoc_insertion_point(field_add:to.PerformRealTimeQCResponse.testReadings)
  return testreadings_.Add();
}
::google::protobuf::RepeatedPtrField< ::to::SensorReadings >*
PerformRealTimeQCResponse::mutable_testreadings() {
  // @@protoc_insertion_point(field_mutable_list:to.PerformRealTimeQCResponse.testReadings)
  return &testreadings_;
}
const ::google::protobuf::RepeatedPtrField< ::to::SensorReadings >&
PerformRealTimeQCResponse::testreadings() const {
  // @@protoc_insertion_point(field_list:to.PerformRealTimeQCResponse.testReadings)
  return testreadings_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)
