// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reading.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "reading.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace to {

void protobuf_ShutdownFile_reading_2eproto() {
  delete Reading::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_reading_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_reading_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_reading_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  Reading::default_instance_ = new Reading();
  Reading::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_reading_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_reading_2eproto_once_);
void protobuf_AddDesc_reading_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_reading_2eproto_once_,
                 &protobuf_AddDesc_reading_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_reading_2eproto {
  StaticDescriptorInitializer_reading_2eproto() {
    protobuf_AddDesc_reading_2eproto();
  }
} static_descriptor_initializer_reading_2eproto_;
#endif

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Reading::kTimeFieldNumber;
const int Reading::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Reading::Reading()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:to.Reading)
}

void Reading::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Reading::Reading(const Reading& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:to.Reading)
}

void Reading::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  time_ = 0;
  value_ = 0;
}

Reading::~Reading() {
  // @@protoc_insertion_point(destructor:to.Reading)
  SharedDtor();
}

void Reading::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void Reading::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Reading& Reading::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_reading_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_reading_2eproto();
#endif
  return *default_instance_;
}

Reading* Reading::default_instance_ = NULL;

Reading* Reading::New(::google::protobuf::Arena* arena) const {
  Reading* n = new Reading;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Reading::Clear() {
// @@protoc_insertion_point(message_clear_start:to.Reading)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Reading, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Reading*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(time_, value_);

#undef ZR_HELPER_
#undef ZR_

}

bool Reading::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:to.Reading)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float Time = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_Value;
        break;
      }

      // optional float Value = 2;
      case 2: {
        if (tag == 21) {
         parse_Value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:to.Reading)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:to.Reading)
  return false;
#undef DO_
}

void Reading::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:to.Reading)
  // optional float Time = 1;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->time(), output);
  }

  // optional float Value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:to.Reading)
}

int Reading::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:to.Reading)
  int total_size = 0;

  // optional float Time = 1;
  if (this->time() != 0) {
    total_size += 1 + 4;
  }

  // optional float Value = 2;
  if (this->value() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Reading::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Reading*>(&from));
}

void Reading::MergeFrom(const Reading& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:to.Reading)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.time() != 0) {
    set_time(from.time());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void Reading::CopyFrom(const Reading& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:to.Reading)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reading::IsInitialized() const {

  return true;
}

void Reading::Swap(Reading* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Reading::InternalSwap(Reading* other) {
  std::swap(time_, other->time_);
  std::swap(value_, other->value_);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string Reading::GetTypeName() const {
  return "to.Reading";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Reading

// optional float Time = 1;
void Reading::clear_time() {
  time_ = 0;
}
 float Reading::time() const {
  // @@protoc_insertion_point(field_get:to.Reading.Time)
  return time_;
}
 void Reading::set_time(float value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:to.Reading.Time)
}

// optional float Value = 2;
void Reading::clear_value() {
  value_ = 0;
}
 float Reading::value() const {
  // @@protoc_insertion_point(field_get:to.Reading.Value)
  return value_;
}
 void Reading::set_value(float value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:to.Reading.Value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace to

// @@protoc_insertion_point(global_scope)
