package com.epocal.epoctest;

/**
 * Created by bmate on 7/19/2017.
 * Received from testcontroller
 * Numbering used in error messages in UX
 */

public enum TestStatusErrorType {
    UNKNOWN(0),
    COMMUNICATIONFAILED(1),
    READERNOCOMPATIBLE(2),
    HCMERROR(3),
    READERERROR(4),
    READERBATTERYLOW(5),
    EQCFAILED(6),
    LOWTEMPERATURELIMIT(7),
    HIGHTEMPERATURELIMIT(8),
    HIGHPRESSURELIMIT(9),
    LOWPRESSURELIMIT(10),
    AMBIENTPRESSURESENSORFAILEDQC(11),
    READERNEEDMAINTENANCE(12),
    REDOEQC(13),
    FLUIDDETECTEDINCARD(14),
    UNABLEREADCARDBARCODE(15),
    INVALIDCARDBARCODE(16),
    INVALIDCARDMANUFACTUREDATE(17),
    CARDEXPIRED(18),
    CARDTYPENOTSUPPORTED(19),
    READERREQUIRESUPGRADE(20),
    NOTESTENABLEFORCARDTYPE(21),
    CARDINSERTEDWHENMOTORMOVING(22),
    CARDINSERTEDNOTPROPERLY(23),
    EXCEEDMAXTEST(24),
    OLDCARDINREADER(25),
    ERROROCCURREDTESTSTOP(26),
    HEMATOCRITLOWRESISTANCE(27),
    EARLYINJECTION(28),
    HUMIDITYCHECKFAILED(29),
    REALTIMEQCFAILED(30),
    FLUIDICSCHECKFAILED(31),
    SAMPLEINJECTEDTOOFAST(32),
    SAMPLEINJECTEDTOOSLOWLY(33),
    SAMPLINGTIMEOUT(34),
    CALIBRATIONFLUIDICSNOTDETECTED(35),
    THERMALQCFAILED(36),
    CARDREMOVEDDURINGTEST(37),
    SAMPLEDELIVERY(38),
    ENDTESTAFTERTESTBEGUN(39),
    UNABLETOCONNECT(40),
    REFERENCEBUBBLE(41);
    public final int value;

    TestStatusErrorType(int value) {
        this.value = Integer.valueOf(value);
    }

    public static TestStatusErrorType convert(int value) {
        return TestStatusErrorType.values()[value];
    }

}
